### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Otabiel** [geaxgx/depthai_blazepose#19]
Hi, I've just have a question for the two parameters : `lm_input_length` & `pd_input_length`
You have addressed to them static value, but what does they mean ? Because I saw that letter you used those value to divide the landmarks resulted by the camera

Thanks in advance

**Comment by Otabiel** [comment]
Hi, thanks for your answer !

If I understand correctly, in the execution of an image processing. You will first apply the pd_model, to found where the body is in the image to avoid non necessary process. Then you will apply the landmark model to found the landmarks in the image. But this output that you catch in the variable `res` in the `next_frame` function is not normalize, because is not at the size of the full image, and you have to readapt it to the correct size. Is it right ?

**Comment by geaxgx** [comment]
This is what I explain here: https://github.com/geaxgx/depthai_blazepose#inferred-3d-vs-measured-3d

The important point to understand is that the mediapipe landmark model is able to infer 3D landmarks from 2D images (I call these as "inferred 3D landmarks"). That may sound like a bit of magic, but I guess google used synthetic data to train their model. Of course, you can't expect real accuracy from these landmarks. Also these landmarks are not absolute (the model can't tell you that for instance the left shoulder is at 5 meters from the camera) but relative to a reference point, the middle point between the hips (the model can estimate a relative delta x,y,z relative to the mid hips).
Now, if you set the xyz mode when running my script, you can IN ADDITION to the inferred 3D landmarks, get from the depth raw data, the real 3D absolute position of this reference point. So you have on one side the body landmarks relative to the reference point and on the other side the absolute position of the reference point. By combining these 2 types of information, you can get an estimatation of the 3D absolute position of each landmark.
This combination task is done there: https://github.com/geaxgx/depthai_blazepose/blob/a3ce15a25c82f4663e4d263c99d7f83ece59ab64/BlazeposeRenderer.py#L123
```
            if self.show_3d == "mixed":  
                if body.xyz_ref:
                    """
                    Beware, the y value of landmarks_world coordinates is negative for landmarks 
                    above the mid hips (like shoulders) and negative for landmarks below (like feet).
                    The y value of (x,y,z) coordinates given by depth sensor is negative in the lower part
                    of the image and positive in the upper part.
                    """
                    translation = body.xyz / 1000
                    translation[1] = -translation[1]
                    if body.xyz_ref == "mid_hips":                   
                        points = points + translation
                    elif body.xyz_ref == "mid_shoulders":
                        mid_hips_to_mid_shoulders = np.mean([
                            points[mpu.KEYPOINT_DICT['right_shoulder']],
                            points[mpu.KEYPOINT_DICT['left_shoulder']]],
                            axis=0) 
                        points = points + translation - mid_hips_to_mid_shoulders   
```
body.xyz contains the absolute 3D position of the reference point as measured from the raw depth data.
The reference point is the mid hips whenever the mid hips is visible in the image, otherwise we use the middle of the shoulders as the reference point.

So, note that by setting the xyz mode, my script configure the pipeline to get the depth raw data, but I rely on this depth data to measure the position of only one point, the reference point. FYI, the first link above explain why I cannot directly measure from this depth data the absolute position of every landmark.

I hope I managed to make things a bit clearer :-)

**Comment by Otabiel** [comment]
Many thanks ! Your explaination were perfectly clear :-D

And your script inspire me for making something more accurate for my use case. And now I understand better the workflow of your script :+1: 

I got a last question, have you try to manage the little clitch that the model have ? Like maybe tresholding the changes between two frame to avoid those little clitch ? And if I want to try to make something is this in your `template_manager_script.py` that I should take a look ?

**Comment by Otabiel** [comment]
I'm sorry to come again to you, I've tried to copy the almost totality of your script manager setup. But when I try to execute it, it stay blocked in waiting for the 'from_post_pd_nn'. I'm say that because de last log message in trace mode that I have is : 
`Manager sent thumbnail config to pre_pd manip`

But when I'm comparing your pipeline creation, and mine, I see no difference 
```python
      print("Creating Pose Detection pre processing image manip...")
      pre_pd_manip = pipeline.create(dai.node.ImageManip)
      pre_pd_manip.setMaxOutputFrameSize(self.pd_input_length * self.pd_input_length * 3)
      pre_pd_manip.setWaitForConfigInput(True)
      pre_pd_manip.inputImage.setQueueSize(1)
      pre_pd_manip.inputImage.setQueueSize(False)

      print("Linking RGB to pre process image manip")
      cam_rgb.preview.link(pre_pd_manip.inputImage)

      print("Linking internal script for pre processing image manip..")
      script_manager.outputs['pre_pd_manip_cfg'].link(pre_pd_manip.inputConfig)

      print("Creating Pose Detection Neural Network...")
      pd_nn = pipeline.create(dai.node.NeuralNetwork)
      pd_nn.setBlobPath(self.pd_model)
      pd_nn.setNumInferenceThreads(2)
      pre_pd_manip.out.link(pd_nn.input)

      print("Creating Pose Detection post processing Neural Network...")
      post_pd_nn = pipeline.create(dai.node.NeuralNetwork)
      post_pd_nn.setBlobPath(self.pp_model)
      pd_nn.out.link(post_pd_nn.input)
      post_pd_nn.out.link(script_manager.inputs['from_post_pd_nn'])
```

I've implented two cameras in the same pipeline, one depth and one rgb, and if I don't use the scripts it works. So the problem is in the setup of your script use.. 

Sorry for question spamming.. but I'm very lost...

**Comment by geaxgx** [comment]
I am currently on holydays, only reading mails once in a while. What do you mean by "clitch" ? If you mean that the drawn landmarks are not superimposed on their corresponding body parts (specially noticeable with the head landmarks), I am afraid that it can't be improved. It is due to the process of converting the original tflite model into openvino float 16 model, whare precision and accuracy have been lost.

**Comment by Otabiel** [comment]
I'll give a look a this so ! Many thanks for your availability. I think that I have all the keys to continue my project aahah

I'll mention you in the thanks of my bachelor ! 
Enjoy your vacation :-)
