### ISSUE TITLE
Explanation about the Model Optimizer params?

### ISSUE THREAD

**Issue by WayneLin015** [geaxgx/depthai_blazepose#6]
Where is the place in the code that do this processing?

**Comment by geaxgx** [comment]
Sorry for the late reply.
This processing is not done in the python code. It is done in the first layers of the models, precisely because when we convert the models from tensorflow to openvino IR, we specify the right arguments to the model optimizer mo_tf.py (for instance,` --reverse_input_channels --mean_values [127.5,127.5,127.5] --scale_values [127.5,127.5,127.5]` for the pose detection model).

**Comment by WayneLin015** [comment]
Thank for reply! I am not familiar to openvino, thx for explanation. Yours processing code help me a lot.

**Comment by geaxgx** [comment]
On this version, where both the pose detection and landmark neural networks are run on each frame, I get around 12 fps. But I am working on a version which works like the original mediapipe version, ie the result of landmarks on frame n can replace the pose detection inference on frame n+1. It means that pose detection is only run once in a while. With this version, I get 17 fps. I will update my repo when the scripting node capability of depthai will be officially released (currently in alpha).

**Comment by WayneLin015** [comment]
looking forward to your new repo !!
Thanks a lot!
