### ISSUE TITLE
About the support for depthai==2.7.1.0

### ISSUE THREAD

**Issue by PINTO0309** [geaxgx/depthai_blazepose#9]
I'm working on a logic fix to make it compatible with the latest depthai package (2.7.1.0). I'd like to issue a pull request to your repository if I can. :smiley: 
https://github.com/PINTO0309/depthai_blazepose/commit/d5cd3f9e3d82afcc9f88990d192c7af31da67c6e

I've already got everything working properly except Edge-only, but I'm wondering how to fix the following part. If you know of a way to do this, could you please let me know?
https://github.com/geaxgx/depthai_blazepose/blob/b8cc80c6a1645a1fed57a3a929d2dea04746fee9/BlazeposeDepthaiEdge.py#L189-L191

The reason why I want to fix this is because another engineer reported an issue that the latest OAK-D does not work properly with depthai==2.3.0. I feel that I want everyone in the world to enjoy your wonderful repository.

- Discord issue
https://discord.com/channels/790680891252932659/799407361986658354/865952356659494932
https://discord.com/channels/790680891252932659/799407361986658354/866090959175024640
https://discord.com/channels/790680891252932659/799407361986658354/866092002923511808

I have successfully gotten it to work with 2.7.1.0 if it is not FullEdge.
![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/33194443/126068795-7f0c23c2-01b4-48c7-960d-416d0c052b13.gif)

**Comment by geaxgx** [comment]
Hi @PINTO0309 ! Happy to see you here :-)
Actually I am also working on an update of my repo. In this update, I want to add the possibility to fetch the real 3D coordinates of the hips center (for device compatible like OAK-D). It is working in Host mode but unfortunately not in Edge mode yet. You know the Edge mode relies on the depthai scripting node capability and it is still an alpha feature (that's why the requirement.txt uses a specific version of depthai). Luxonis team is working on fixing some remaining bugs (https://discord.com/channels/790680891252932659/828645636744282153/865867717754880010).
I hope we should not wait a long time before these bugs are fixed (Luxonis team is very efficient!).

But if your need or your friend's need is urgent, I can accept your pull request. Just tell me.

**Comment by PINTO0309** [comment]
Thank you! I understand! I'll wait for the Luxonis fix.
